apiVersion: v1
kind: Secret
metadata:
  name: fastapi-server-credentials
  namespace: default
stringData:
  .env: |
    SECRET=SECRET
    DATABASE_URL=postgresql+asyncpg://postgres:postgres@postgres-service/test_fastapi
    REDIS_HOST=redis://redis-service:6379/0