apiVersion: v1
kind: Secret
metadata:
  name: postgres-db-credentials
  namespace: default
data:
  user: cG9zdGdyZXM=                # postgres
  password: cG9zdGdyZXM=              # postgres
  host: cG9zdGdyZXMtc2VydmljZQ==  # service name in the postgres-service.yml
  db: dGVzdF9mYXN0YXBp                      # test_fastapi
